### ISSUE TITLE
开始请求TTS:  LLM 数据返回错误！

### ISSUE THREAD

**Issue by JoneZhu** [wangzongming/esp-ai#4]
=== 开始请求TTS:  LLM 数据返回错误！  ===
提问失败:  {
  header: {
    code: 11200,
    message: 'AppIdNoAuthError:(16:26:07.442) tokens.total',
    sid: 'cht000b1d60@dx190a60caed1b809560',
    status: 2
  }
}
-> 讯飞 tts服务连接成功！
-> TTS 转换完毕

**Comment by JoneZhu** [comment]
讯飞的错误码解释如下 ：https://www.xfyun.cn/document/error-code?code=11200
<img width="968" alt="image" src="https://github.com/user-attachments/assets/cd9d98f8-cde4-42fd-8617-ea990152ed86">

**Comment by JoneZhu** [comment]
原因分析：
1. 返回此错误的接口是 wss://spark-api.xf-yun.com/v3.5/chat
2. 讯飞的解释是服务没有授权
3. 从后台的左侧可以看到服务的说明
<img width="663" alt="image" src="https://github.com/user-attachments/assets/44529c53-533b-4123-943a-c2481c702040">

**Comment by wangzongming** [comment]
服务端配置贴一下，可能是你的发音人设置不对

**Comment by JoneZhu** [comment]
返回此错误的接口是 wss://spark-api.xf-yun.com/v3.5/chat
讯飞的解释是服务没有授权
通过代码查询 wss://spark-api.xf-yun.com/v3.5/chat 对应的是LLM ，其中3.5 对应的是 SparkMax ，SparkMax 没有额度，在购买额度页面可以申请实名认证之后领取SparkMax额度， 此问题解决。
![image](https://github.com/user-attachments/assets/298f4959-388d-4482-a1e1-fd02f52421d6)
