### ISSUE TITLE
audio_tools::I2SConfigESP32V1类中缺少channel_format和auto_clear

### ISSUE THREAD

**Issue by chadyi** [wangzongming/esp-ai#7]
d:\arduinocode\libraries\esp-ai\src\esp-ai.cpp: In member function 'void ESP_AI::speaker_i2s_setup()':
d:\arduinocode\libraries\esp-ai\src\esp-ai.cpp:137:12: error: 'class audio_tools::I2SConfigESP32V1' has no member named 'channel_format'
  137 |     config.channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT;
      |            ^~~~~~~~~~~~~~
d:\arduinocode\libraries\esp-ai\src\esp-ai.cpp:141:12: error: 'class audio_tools::I2SConfigESP32V1' has no member named 'auto_clear'
  141 |     config.auto_clear = true;
      |            ^~~~~~~~~~

exit status 1

Compilation error: exit status 1

**Comment by wangzongming** [comment]
该问题原因：

1. esp 开发板不是 2.x 版本, 
2. 使用的开发板不是 esp32s3
