### ISSUE TITLE
联网成功后 停留在初始化没有动静

### ISSUE THREAD

**Issue by chadyi** [wangzongming/esp-ai#8]
扬声器采样率：16000

[I] AudioTypes.h : 127 - in: sample_rate: 16000 / channels: 1 / bits_per_sample: 16
[I] AudioTypes.h : 127 - out: sample_rate: 16000 / channels: 1 / bits_per_sample: 16
[I] AudioTypes.h : 127 -  sample_rate: 16000 / channels: 1 / bits_per_sample: 16
[I] I2SConfigESP32.h : 80 - rx/tx mode: TX_MODE
[I] I2SConfigESP32.h : 81 - port_no: 0
[I] I2SConfigESP32.h : 82 - is_master: Master
[I] I2SConfigESP32.h : 83 - sample rate: 16000
[I] I2SConfigESP32.h : 84 - bits per sample: 16
[I] I2SConfigESP32.h : 85 - number of channels: 1
[I] I2SConfigESP32.h : 86 - signal_type: Digital
[I] I2SConfigESP32.h : 88 - i2s_format: I2S_MSB_FORMAT
[I] I2SConfigESP32.h : 90 - auto_clear: true
[I] I2SConfigESP32.h : 92 - use_apll: true
[I] I2SConfigESP32.h : 97 - buffer_count:8
[I] I2SConfigESP32.h : 98 - buffer_size:1024
[I] I2SConfigESP32.h : 103 - pin_bck: 16
[I] I2SConfigESP32.h : 105 - pin_ws: 17
[I] I2SConfigESP32.h : 107 - pin_data: 15

**Comment by wangzongming** [comment]
应该服务端没有启动成功，或者服务端ip配置错误。
